### ISSUE TITLE
Autoscaling not available on GCP

### ISSUE THREAD

**Issue by yilindu27-na** [unionai-oss/deploy-flyte#24]
We used the terraform for GCP to create a Flyte cluster. We found that the node pool on the GKE cluster cannot be scaled down because "pod is blocking scale down because it’s not backed by a controller."

**For more details:
GCP:**
Pod is blocking scale down of underutilized node because it doesn’t have a controller, such as a deployment or replicaset. Refer to logs for more details. 
Recommended actions
Set annotation "cluster-autoscaler.kubernetes.io/safe-to-evict": "true" for Pod or define a controller, such as a deployment or replicaset, for the Pod

**Log:**
noScaleDown: {
......
reason: {
messageId: "no.scale.down.node.pod.kube.system.unmovable"}
}

**Comment by davidmirror-ops** [comment]
I'm curious what Pod(s) in the cluster would not be backed by a controller.
The Flyte Taks pods are backed by the flytepropeller controller tied to the flyteworkflow CRD but not sure if that qualifies for GKE's Autoscaler. 

According to [this](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node) it's likely that it refers to a Pod in the `kube-system` namespace. 

Could you share the output of

`kubectl get pods -n kube-system -o wide`

**Comment by yilindu27-na** [comment]
I'm not exactly sure which pod to look at. We are looking into that right now. Is there a particular log I can share with you?

In general though we tried to setup autoscaling using the following two methods which neither worked. But when we try this with a separate (non-flyte) GKE cluster at least the first method works. Are either of these methods the right way to setup autoscaling with using this terraform? 


Method 1: updating node pool autoscaling params in gke.tf. When we do this we see that  the changes to the cluster are applied but autoscaling doesnt actually happen.

 ```
node_pools = [
    {
      name         = "default"
      machine_type = "e2-standard-4"
      total_min_count    = 2
      total_max_count    = 4
      # Set to true if you want to enable Image Streaming. Learn more: https://cloud.google.com/kubernetes-engine/docs/how-to/image-streaming to speed up pulling of images
      enable_gcfs  = false 
      autoscaling = true
    }
  ]

```

In the second method:

```
cluster_autoscaling = {
    enabled             = true
    autoscaling_profile = "BALANCED"
    max_cpu_cores       = 6
    min_cpu_cores       = 4
    max_memory_gb       = 16
    min_memory_gb       = 8
    gpu_resources       = []
    auto_repair         = true
    auto_upgrade        = true
    disk_size           = 100
    disk_type           = "pd-standard"
    image_type          = "COS_CONTAINERD"    
  }

```

p.s. we know these two settings are achieving different autoscaling configurations, at this point we just are trying to make it work.

**Comment by davidmirror-ops** [comment]
Can you check what Pods are scheduled in the node you want CA to remove?

`kubectl get pods --all-namespaces --field-selector spec.nodeName=<NODE_NAME>
`

Then we can figure out what to do depending on how they match the restrictions mentioned in CA's docs

**Comment by yilindu27-na** [comment]
Thank you for your reply!

We figured out which pods are blocking the autoscaling by looking at the autoscaler log:

Log:
noScaleDown: {
nodes: [
0: {
node: {4}
reason: {
messageId: "no.scale.down.node.pod.kube.system.unmovable"
parameters: [
0: "kube-dns-..."
]}}
1: {
node: {4}
reason: {
messageId: "no.scale.down.node.pod.kube.system.unmovable"
parameters: [
0: "l7-default-backend-..."
]}}
2: {
node: {4}
reason: {
messageId: "no.scale.down.node.pod.kube.system.unmovable"
parameters: [
0: "kube-dns-..."
]}}

And, we tried to set PDBs for those pods but its not working.

**Comment by davidmirror-ops** [comment]
sorry for the delay, somehow I missed the notification.

So those don't seem to be Flyte pods. But in any case, I just found out that apparently, the default K8s plugin config that Flyte uses includes [an annotation](https://github.com/flyteorg/flyte/blob/81afb76b44931d827f8e898d097a7e8054a5b836/flyteplugins/go/tasks/pluginmachinery/flytek8s/config/config.go#L32C5-L32C60) that could prevent CA to work

Could you check the annotations on those Pods?

**Comment by yilindu27-na** [comment]
Yes, there are some kube-system pods, namely kube-dns, blokcing the down scaling but we kind of solved this by having two node pools. So, at least, one pool can be scaled down to zero.

**Comment by davidmirror-ops** [comment]
got it, thanks for sharing!
